# print("hello \bharat")
# print("hello\bharat")
# print("hello\\bharat")

# print("hello\tworld")
# print("hello   world")
# print("hello   \tworld")
# print("\thelloworld")
# print("hello\t" "world")
# print("hello   world")

# print('py\ron')
# print('pyth\ron')
# print('pythpy\rongo')
# print('pythpyu\rongo')
# print('pythpyu\rongostur')
# print('pythpyusfuh\rongostur')

# print("My name is \r sumanth")
# print("My name is\r sumanth")

# print("hello\ankith")
# print("hello\aankith")
# print("hello\\ankith")
# print("hello  \bankith")
# print("hello\cankith")
# print("hello\dankith")
# print("hello\eankith")
# print("hello\fun")
# print("hello\fair")
# print("hello\rair")
# print("hello\tair")
# print("hello\vair")
# print("hello\vsumanth")
# print("hello\nsumanth")
print("Hello\Umbrella")
print("Hello\Pmbrella")
print("Hello\Numbrella")

